serverConfigs:
 prefix : 'CORE_'
 isMaster : true
 portOffset : 0
 httpPort : 8080
 httpsPort : 8085
 adminPort : 9463
 caddyPort : 8082
 readTimeOut : 20
 writeTimeOut : 20
 certificateFile : 'resources/security/server.pem'
 keyFile : 'resources/security/server.key'
 JWTPrivateKeyFile : 'resources/security/private.key'
 JWTPublicKeyFile : 'resources/security/public.key'
 JWTExpirationDelta : 72
 caddyPath : 'webapps'
 caddyFile : 'webapps/Caddyfile'
 logsDirectory : 'logs'
 enableAccessLogs : true

redisConfigs:
 serverUrl : localhost
 serverPort : 6379
 password : root
 db : 0

dbConfigs:
 -
  name : vamps
  dialect : mysql
  username : root
  password : root
  dbname : dashboard
  address : 'localhost:3306'
  parameters : ""
 -
  name : userstore
  dialect : mysql
  username : root
  password : root
  dbname : dashboard
  address : 'localhost:3306'
  parameters : ""

